Refine ci (#15)
* Github Actions vol 1

* fix typo

* Github Actions vol 2

* add go build tags for neutrino and wtclientrpc

* Set GODEBUG netdns=cgo in both builders

* test

* a set of minor changes

* Various build fixes

* Fix final broken build

* Trigger build…

* Add simple sanity-checks stub

* Fix path for docker load

* Missing * added 🙄

* Print info about built images

* Github discriminates against I.T. !

* Remove havoc-causing CMD

* remove unnecessary build tags

* remove unnecessary comment

* Add monitoring variant to 0.8

* remove flags not neessary for 0.8

* TODO-comment fix

* update patch file

* Make binaries reproducible again!

* Add monitoring variant to 0.7

* Test monitoring variant build on GH actions

* fmt

* update patch file

* Add keybase to GPG key download locations

* Add integrity checks for build.sh file for 0.7/  &  0.8/

* fix 0.7/build.sh checksum

* Test if variants apply ok

* Attemp one at automatic deploy

* fix for missing variants

* limit test.yml to build for branches only

* remove remaining and invalid matrix.ver rferences

* Make names easier to distinguish

* Mark GH releases as a pre-release by default

* bitcoind -> lnd

* print GH ref

* set TAG as a missing var

* Handle Docker not handling plus-signs in tags

* add files needed by github readme sync action

* Add setting up missing env var BUILD

* Upade .patch files for 0.7 & 0.8

* remove build.sh file verification for variants

* Tweak names of artifacts uploaded to GH release

* fix checksum printing

* get rid of Travis

* hope gzip's suffix is ok now

* Fix the sudden gzip's suffix issue.  Last attempt today…

* Add experimental variant to lnd

diff --git a/0.5/Dockerfile b/0.5/Dockerfile
--- a/0.5/Dockerfile
+++ b/0.5/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.11-alpine3.9 as builder
+FROM golang:1.12-alpine3.10 AS builder
 
 # Force Go to use the cgo based DNS resolver. This is required to ensure DNS
 # queries required to connect to linked containers succeed.
@@ -7,15 +7,42 @@ ENV GODEBUG netdns=cgo
 # Install dependencies
 RUN apk add --no-cache --update alpine-sdk \
     git \
+    gnupg \
     gcc \
     ca-certificates \
     upx
 
-# fetch lnd source code
-# TODO: Add content hash validation upon source download; see lncm/docker-lnd#5
-RUN git clone -b v0.5.2-beta --depth 1 https://github.com/lightningnetwork/lnd
+ENV TAG v0.5.2-beta
+ENV KEYS F8037E70C12C7A263C032508CE58F7F8E20FD9A2
 
-ARG goos
+# Try to fetch keys from keyservers listed below.  On first success terminate with `exit 0`.  If loop is not interrupted,
+#   it means all attempts failed, and `exit 1` is called.
+RUN for SRV in hkp://p80.pool.sks-keyservers.net:80  ha.pool.sks-keyservers.net  keyserver.pgp.com  pgp.mit.edu; do \
+        timeout 9s  gpg  --keyserver "${SRV}"  --recv-keys ${KEYS}  >/dev/null 2<&1 && \
+            { echo "OK:  ${SRV}" && exit 0; } || \
+            { echo "ERR: ${SRV} fail=$?"; } ; \
+    done && exit 1
+
+RUN gpg --list-keys
+
+RUN mkdir -p /go/src/
+
+ENV DIR /go/src/lnd/
+
+# Fetch lnd source code
+RUN cd /go/src/ && \
+    git clone  -b "${TAG}"  --depth=1  https://github.com/lightningnetwork/lnd
+
+WORKDIR /go/src/lnd/
+
+# NOTE: The fallback condition is a hack around @Roasbeef's "key hygiene".  A manual attempt at accepting expired keys
+#       through git verify-tag; What can possibly go wrong? 😅
+#       More: https://github.com/lightningnetwork/lnd/issues/3507#issuecomment-532414524
+RUN git verify-tag "${TAG}" || \
+    { git verify-tag --raw "${TAG}" 2>&1 | grep EXPKEYSIG && echo "Accepting expired key!"; }
+
+
+ARG goos=linux
 ENV GOOS ${goos}
 
 ARG goarch
@@ -27,18 +54,17 @@ ENV GOARM ${goarm}
 RUN echo "GOOS:${GOOS} GOARCH:${GOARCH} GOARM:${GOARM}"
 
 # Build the binaries
-RUN cd lnd \
-    && make install
+RUN make install
 
-# move arm binaries to the "standard" location, for ease of copying in the next stage
-RUN if [[ -d /go/bin/linux_arm/ ]]; then mv /go/bin/linux_arm/* /go/bin/; rmdir /go/bin/linux_arm/; fi
+# Move arm[64] binaries to the "standard" location, for ease of copying in the next stage
+RUN if [ -d /go/bin/linux_* ]; then mv /go/bin/linux_*/* /go/bin/  &&  rmdir /go/bin/linux_* ; fi
 
-# shrink output binaries
+# Shrink output binaries
 RUN upx -v /go/bin/*
 
 
 # Start a new, final image
-FROM alpine:3.9 as final
+FROM alpine:3.10 as final
 
 LABEL maintainer="Damian Mee (@meeDamian)"
 
@@ -55,4 +81,3 @@ EXPOSE 8080 9735 10009
 
 # Specify the start command and entrypoint as the lnd daemon.
 ENTRYPOINT ["lnd"]
-CMD ["lnd"]
diff --git a/0.6/Dockerfile b/0.6/Dockerfile
--- a/0.6/Dockerfile
+++ b/0.6/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.12-alpine3.9 as builder
+FROM golang:1.12-alpine3.10 as builder
 
 # Force Go to use the cgo based DNS resolver. This is required to ensure DNS
 #   queries required to connect to linked containers succeed.
@@ -14,42 +14,57 @@ RUN apk add --no-cache --update alpine-sdk \
     ca-certificates \
     upx
 
-ENV TAG v0.6-beta
-ENV FINGERPRINT F8037E70C12C7A263C032508CE58F7F8E20FD9A2
+ENV TAG v0.6.1-beta
+ENV KEY F8037E70C12C7A263C032508CE58F7F8E20FD9A2
 
-ARG arch
-ENV LNDBUILDSYS ${arch}
+# Try to fetch keys from keyservers listed below.  On first success terminate with `exit 0`.  If loop is not interrupted,
+#   it means all attempts failed, and `exit 1` is called.
+RUN for SRV in hkp://p80.pool.sks-keyservers.net:80  ha.pool.sks-keyservers.net  keyserver.pgp.com  pgp.mit.edu; do \
+        timeout 9s  gpg  --keyserver "${SRV}"  --recv-keys ${KEY}  >/dev/null 2<&1 && \
+            { echo "OK:  ${SRV}" && exit 0; } || \
+            { echo "ERR: ${SRV} fail=$?"; } ; \
+    done && exit 1
+
+RUN gpg --list-keys
+
+RUN mkdir -p /go/src/
+
+ENV DIR /go/src/lnd/
 
 # Fetch lnd source code
-RUN git clone -b ${TAG} --depth 1 https://github.com/lightningnetwork/lnd
+RUN cd /go/src/ && \
+    git clone  -b "${TAG}"  --depth=1  https://github.com/lightningnetwork/lnd
 
-RUN cd lnd \
-    # Import @roastbeef's key
-    && curl -s https://keybase.io/roasbeef/pgp_keys.asc | gpg --import \
-    \
-    # Make sure we have the right key
-    && gpg --list-keys ${FINGERPRINT} \
-    \
-    # Verify that pulled release has been signed by the only key we've added
-    && git verify-tag ${TAG}
+WORKDIR /go/src/lnd/
+
+# NOTE: The fallback condition is a hack around @Roasbeef's "key hygiene".  A manual attempt at accepting expired keys
+#       through git verify-tag; What can possibly go wrong? 😅
+#       More: https://github.com/lightningnetwork/lnd/issues/3507#issuecomment-532414524
+RUN git verify-tag "${TAG}" || \
+    { git verify-tag --raw "${TAG}" 2>&1 | grep EXPKEYSIG && echo "Accepting expired key!"; }
+
+
+ARG arch=linux-amd64
+ENV LNDBUILDSYS ${arch}
+ENV GO111MODULE on
+
 
 # Patch for `release.sh` using `shasum` on the last line:
 #   `shasum` package is not available on Alpine, and we really don't care for checksums here
 RUN touch /bin/shasum && chmod +x /bin/shasum
 
 # Build the binaries
-RUN cd lnd \
-    && ./release.sh ${TAG}
+RUN ./release.sh ${TAG}
 
 # Uncompress binaries to the "standard" location, for ease of copying in the next stage
-RUN tar -xvzf "lnd/lnd-${TAG}/lnd-${arch}-${TAG}.tar.gz" --strip=1 -C /go/bin/
+RUN tar -xvzf "lnd-${TAG}/lnd-${arch}-${TAG}.tar.gz"  --strip=1  -C /go/bin/
 
 # Shrink output binaries
 RUN upx -v /go/bin/*
 
 
 # Start a new, final image
-FROM alpine:3.9 as final
+FROM alpine:3.10 as final
 
 LABEL maintainer="Damian Mee (@meeDamian)"
 
@@ -66,4 +81,3 @@ EXPOSE 8080 9735 10009
 
 # Specify the start command and entrypoint as the lnd daemon.
 ENTRYPOINT ["lnd"]
-CMD ["lnd"]
